### PR TITLE
Feature/loginform

### PR DESCRIPTION
**Pull request by Soulful0**
Login Form has been completed for the user to log in to be able to have the functionality for viewing saved plant guides.

### CODE REVIEW

**Review by ajfizzle — DISMISSED** [review]
Looks great!!!!!

**Review by ajfizzle — DISMISSED** [review]
Perfect!!!!

**Review by ajfizzle — DISMISSED** [review]
Looks great!!!

**Review by tcarocci — APPROVED** [review]
Looks great!

**Review by tcarocci — DISMISSED** [review]

**Review by vbadger7 — COMMENTED** [review]
no issues

**Review by ajfizzle — APPROVED** [review]
Look okay

**Pull request merged**
